import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
// NOTE: Removed unused 'hasLocale', 'routing', and 'notFound' imports
import { NextIntlClientProvider } from "next-intl"; 
import Navbar from "@/components/app/Navbar";
import { AuthProvider } from '../../context/userContext';
import { PropsWithChildren } from "react"; // Import necessary React types

// --- TYPE DEFINITION ---

// Define the exact type for the Layout component props
// Since you only need 'children', PropsWithChildren is enough.
type LayoutProps = PropsWithChildren<{
  // params has been removed from this type
}>;

// --- FONT DEFINITIONS ---
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// --- METADATA ---
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// --- LAYOUT COMPONENT ---
// The function now only accepts 'children' as prop.
export default function LocaleLayout({ children }: LayoutProps) {
  
  // The logic for accessing locale and validation has been removed.
 
  return (
    // WARNING: Since 'locale' is no longer available, 'lang' attribute is empty. 
    // This may cause issues if not set correctly in your i18n setup.
    <html lang=""> 
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=satoshi@400&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}