import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import Navbar from "@/components/app/Navbar";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { AuthProvider } from '../../context/userContext';
import { ReactNode, PropsWithChildren } from "react"; // Import necessary React types

// --- TYPE DEFINITIONS ---

// 1. Define the dynamic parameters expected from the route
// type Params = {
//   locale: string;
// };

// // 2. Define the exact type for the Layout component props
// // PropsWithChildren adds the 'children: ReactNode' automatically
// type LayoutProps = PropsWithChildren<{
//   params: Params;
// }>;

// --- FONT DEFINITIONS ---
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// --- METADATA ---
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// --- LAYOUT COMPONENT ---
// Removed 'async' keyword as message fetching is not present, making it a standard layout.
export default function LocaleLayout({ children }) {
  
  // Access the locale directly from the resolved params object
 
  return (
    <html   >
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=satoshi@400&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}